"use client";

import { motion } from "framer-motion";
import { LockKeyhole } from "lucide-react";

import { CompletionCard } from "@/features/roadmap/components/CompletionCard";
import { CurrentPhase } from "@/features/roadmap/components/CurrentPhase";
import { GoalCard } from "@/features/roadmap/components/GoalCard";
import { LearningCalendar } from "@/features/roadmap/components/LearningCalendar";
import { MilestoneCard } from "@/features/roadmap/components/MilestoneCard";
import { MonthlyProgress } from "@/features/roadmap/components/MonthlyProgress";
import { RoadmapFilters } from "@/features/roadmap/components/RoadmapFilters";
import { RoadmapHero } from "@/features/roadmap/components/RoadmapHero";
import { RoadmapSidebar } from "@/features/roadmap/components/RoadmapSidebar";
import { RoadmapStats } from "@/features/roadmap/components/RoadmapStats";
import { SkillTree } from "@/features/roadmap/components/SkillTree";
import { TaskCard } from "@/features/roadmap/components/TaskCard";
import { Timeline } from "@/features/roadmap/components/Timeline";
import { WeeklyProgress } from "@/features/roadmap/components/WeeklyProgress";
import { useRoadmap } from "@/features/roadmap/hooks";
import type { Roadmap } from "@/features/roadmap/types";

type RoadmapOverviewProps = {
  roadmap: Roadmap | null;
  recommendations: string[];
  authenticated: boolean;
};

const cardAnimation = {
  initial: { opacity: 0, y: 16 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.35 },
};

export function RoadmapOverview({
  roadmap,
  recommendations,
  authenticated,
}: RoadmapOverviewProps) {
  const { todaysTasks, currentWeekGoal } = useRoadmap(roadmap);

  return (
    <div className="mx-auto w-full max-w-[var(--container-wide)] space-y-8">
      <motion.div {...cardAnimation}>
        <RoadmapHero roadmap={roadmap} authenticated={authenticated} />
      </motion.div>

      {!authenticated ? (
        <EmptyRoadmapState
          title="Sign in to view your roadmap."
          description="Career roadmap progress is stored per account so milestones and tasks stay persistent."
        />
      ) : null}

      {authenticated && !roadmap ? (
        <EmptyRoadmapState
          title="No roadmap generated yet."
          description="Use the roadmap create API to generate a deterministic plan for your current skills and target role."
        />
      ) : null}

      <RoadmapStats roadmap={roadmap} />

      <div className="grid gap-6 xl:grid-cols-[1fr_320px]">
        <div className="space-y-6">
          <RoadmapFilters activePhase={roadmap?.currentPhase ?? null} />
          <div className="grid gap-6 lg:grid-cols-2">
            <CurrentPhase roadmap={roadmap} />
            <CompletionCard roadmap={roadmap} />
          </div>
          <section className="surface-card p-6">
            <h2 className="text-xl font-semibold">Today&apos;s Tasks</h2>
            <div className="mt-5 grid gap-3">
              {todaysTasks.length > 0 ? (
                todaysTasks.map((task) => <TaskCard key={task.id} task={task} />)
              ) : (
                <p className="rounded-2xl border border-dashed border-border p-6 text-sm text-muted-foreground">
                  No active tasks for the current week.
                </p>
              )}
            </div>
          </section>
          <Timeline roadmap={roadmap} />
          <section className="grid gap-4 lg:grid-cols-2">
            {(roadmap?.milestones ?? []).slice(0, 4).map((milestone) => (
              <MilestoneCard key={milestone.id} milestone={milestone} />
            ))}
          </section>
          <SkillTree skills={roadmap?.skillGraph ?? []} />
          <LearningCalendar goals={roadmap?.weeklyGoals ?? []} />
        </div>
        <div className="space-y-6">
          <RoadmapSidebar roadmap={roadmap} />
          <WeeklyProgress goal={currentWeekGoal} />
          <MonthlyProgress goals={roadmap?.monthlyGoals ?? []} />
          <section className="surface-card p-6">
            <h2 className="text-xl font-semibold">Recommended Resources</h2>
            <div className="mt-5 space-y-3">
              {(roadmap?.resources ?? []).slice(0, 4).map((resource) => (
                <GoalCard
                  key={resource.id}
                  label={resource.type}
                  title={resource.title}
                  meta={resource.description}
                />
              ))}
              {recommendations.map((recommendation) => (
                <GoalCard
                  key={recommendation}
                  label="Recommendation"
                  title={recommendation}
                  meta="Generated by deterministic roadmap rules."
                />
              ))}
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}

function EmptyRoadmapState({
  title,
  description,
}: {
  title: string;
  description: string;
}) {
  return (
    <section className="surface-card flex flex-col items-center justify-center px-6 py-14 text-center">
      <LockKeyhole className="size-10 text-primary" aria-hidden="true" />
      <h2 className="mt-4 text-xl font-semibold">{title}</h2>
      <p className="mt-2 max-w-xl text-sm text-muted-foreground">{description}</p>
    </section>
  );
}
